//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Helpers.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Helpers.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server has already  been configured!.
        /// </summary>
        public static string AlreadyConfigured {
            get {
                return ResourceManager.GetString("AlreadyConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server is already running!.
        /// </summary>
        public static string AlreadyRunning {
            get {
                return ResourceManager.GetString("AlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to files on server needs to be defined!.
        /// </summary>
        public static string MissingPathToFiles {
            get {
                return ResourceManager.GetString("MissingPathToFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port needs to be defined!.
        /// </summary>
        public static string MissingPort {
            get {
                return ResourceManager.GetString("MissingPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protocol needs to be defined!.
        /// </summary>
        public static string MissingProtocol {
            get {
                return ResourceManager.GetString("MissingProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server needs to be defined!.
        /// </summary>
        public static string MissingServer {
            get {
                return ResourceManager.GetString("MissingServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Needs Windows XP SP2, Server 2003 or later..
        /// </summary>
        public static string NotSupported {
            get {
                return ResourceManager.GetString("NotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory with files does not exist!.
        /// </summary>
        public static string PathToFilesDirectoryDoesNotExist {
            get {
                return ResourceManager.GetString("PathToFilesDirectoryDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server has not been configured!.
        /// </summary>
        public static string ServerNotConfigured {
            get {
                return ResourceManager.GetString("ServerNotConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server has not been started!.
        /// </summary>
        public static string ServerNotRunning {
            get {
                return ResourceManager.GetString("ServerNotRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port string is wrong!.
        /// </summary>
        public static string WrongPort {
            get {
                return ResourceManager.GetString("WrongPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protocol string is wrong!.
        /// </summary>
        public static string WrongProtocol {
            get {
                return ResourceManager.GetString("WrongProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server string is wrong!.
        /// </summary>
        public static string WrongServer {
            get {
                return ResourceManager.GetString("WrongServer", resourceCulture);
            }
        }
    }
}
